[pyprland]
plugins = ["scratchpads"]

[scratchpads.notes]
animation = "fromTop"
class = "[Oo]bsidian"
command = "uwsm app obsidian"
size = "75% 70%"
lazy = "true"
margin = 180

[scratchpads.code]
animation = "fromTop"
class = "com.nvim"
command = "uwsm app -- ghostty --class=com.nvim -e nvim"
size = "70% 70%"
lazy = "true"
margin = 180

[scratchpads.spotify]
animation = "fromTop"
class = "[Ss]potify"
command = "uwsm app spotify-launcher"
size = "55% 60%"
lazy = "true"
margin = 260
